### ISSUE TITLE
Stream support

### ISSUE THREAD

**Issue by nazar-pc** [Riverline/multipart-parser#1]
Content in case of files uploading can be of arbitrary size.
Can you add support for streams?
I mean accept `$content` of type `string` or `resource` (as returned from `fopen()`).

To start parsing you basically need complete header, everything else can be parse on fly.

**Comment by nazar-pc** [comment]
I'm already working on implementation.
The most basic problem is that requests might be sometimes quite large and thus should be handled as strings in order to avoid going out of memory.

I'll add `::getBodyStream()` that'll unify interface. In this case it would be possible to get both string and stream body when initialized from either string or stream providing 2-way conversion if necessary while work optimally if no conversion needed.

**Comment by KvanSteijn** [comment]
What is the status of this issue?

**Comment by nazar-pc** [comment]
There was no upstream interest as far as I see, so I've implemented another parser basically from scratch for my project and closed PR since it wasn't merged for a long time.

You can find my efficient stream-based parser from [this line](https://github.com/nazar-pc/CleverStyle-Framework/blob/43f0f6b321e567995cfed79885b19ede447a0598/core/traits/Request/Data_and_files.php#L183) and forward. Feel free to use code in your project while respecting license.

I'm not sure there is enough interest in standalone parser of that kind, so I didn't bother to create standalone project. Mentioned code is 100% covered with tests. It doesn't try to follow specification 100%, but rather works with the most common formats generated by browsers and popular tools like cURL.

**Comment by rcambien** [comment]
Sorry, I didn't have time to work on this, to add the stream support and keep it BC with my workflow (parsing email multipart with incoherent end of line). I planned to redo this lib from scratch for an other projet. @nazar-pc, I will check your code when I will start this new project, thanks for the contribution.

**Comment by nazar-pc** [comment]
I can actually decouple mentioned code from the framework into standalone library if there is enough demand.
I've done this few times in past, now framework is more modular than before so this is definitely doable.
