### ISSUE TITLE
Question about redistribute fork

### ISSUE THREAD

**Issue by wehowski** [Riverline/multipart-parser#10]
Hi authors,
first thanks for the great work!

I have forked and extended it into this repo https://github.com/frdl/mime-stub

I would like to submit this repository synchronized to the phpclasses site: https://www.phpclasses.org/package/10457-PHP-This-script-can-be-used-to-generate-self-executin.html

Would this be OK for you? 
I not want to join any contest with this class, bzw. pass it to you...

> <span><span>Hi Manuel, I submitted a class </span><a target="_blank" href="https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.phpclasses.org%2Fpackage%2F10457-PHP-This-script-can-be-used-to-generate-self-executin.html&amp;h=ATOVM5LfemvvTvLle4TCX1IFP5ZITNdkFhICsGMPAA_p5K2qeRUnQ6af9EEtinYYDItdqiwA15j2BVOX08m4hIfqr4p6j9rBRH3vsmDQzJCe4yefLVkjZ3KopmVu3FXdmZ7_ImzwJLkx" rel="nofollow">https://www.phpclasses.org/package/10457-PHP-This-script-can-be-used-to-generate-self-executin.html</a><span> but please again can you wait with thze approval, there is the fowllowing compunction: The class is a fork and extension of another author. First I will ask the original author if it is OK for him if I commit my Extension to your repo, second, if published, I </span><a class="_fcj" href="#">do</a><span> not want to join any contest with this class, is this possible? What </span><a class="_fcj" href="#">do</a><span> you think of submitting such a fork (implementing classes from other authors)? Although I think the license will allow it, I want to stay fair!</span></span>

**Comment by rcambien** [comment]
Hi @wehowski,

No problem, we put the code here so peoplre can can fork it and share it without restrictions.
