### ISSUE TITLE
Error on missing headers

### ISSUE THREAD

**Issue by PaulCombal** [Riverline/multipart-parser#15]
Hello, I've been stuck for a while on an issue, but I've finally found a workaround.
The headers are not present in the resonse content in Symfony, so everytime I want  to use the parser, I'm doing this and praying for it to work.

         $content = $request->getContent();
        
        $boundary = preg_split ('/$\R?^/m', $content);
        if (sizeof($boundary) > 0) {
            $boundary = $boundary[0];
        } else {
            return new Response('Could not find boundary', 500);
        }
        
        $content = 'Content-Type: multipart/form-data; boundary=' . substr($boundary, 2) . "\n\n" . $content;
        $formdata = null;

        try {
            $formdata = new Part($content);
        } catch (\Exception $e) {
            return new Response('Invalid multipart ' . $e->getMessage(), 500);
        }`

Is there a way this can be fixed, or some warning be displayed in the docs as I think most people will use the parser this way..
This is also the only way I could make the backend work for at least Chrome and Firefox.

Thanks

**Comment by rcambien** [comment]
You can use this code as a better solution : 
```php
$formdata = new Part(strval($request));
```
`Request` object provide a `__toString()` method that reconstruct the raw request.
