### ISSUE TITLE
pcre.backtrack_limit

### ISSUE THREAD

**Issue by BenNewman** [Riverline/multipart-parser#19]
Thanks for this library. I was integrating it into my project and found that it was failing with certain requests that included attachments. I tracked it down to the `preg_match` call [here](https://github.com/Riverline/multipart-parser/blob/e6dbac2ddfec1b938423d24c6627586f4444ccb8/src/Riverline/MultiPartParser/Part.php#L108).

The match would fail when the `$subject` passed to `preg_match` exceeded a certain size. The solution is to change the limit via `pcre.backtrack_limit`. Perhaps it's worth mentioning in the readme?

**Comment by rcambien** [comment]
Hi, the problem was already reported with PR #17 
The simple solution is to increase the limit but I'm working on a new version of the parser that avoid this limitation.

**Comment by BenNewman** [comment]
Sorry, I didn't think it had been reported, I only searched within the issues. I'll close this since it's already a known issue.

**Comment by rcambien** [comment]
Hi @BenNewman 
I just released the version 2 of the lib that don't use preg function.
Give it a try !
