### ISSUE TITLE
Dirty repo ?

### ISSUE THREAD

**Issue by orbex** [Riverline/multipart-parser#23]
L.S.,

upon upgrade the vendor from v1.1.10 to v2.0.2 the bitbucket pipeline gave off an error:

```
+ doVendor riverline/multipart-parser
Thu May  2 07:36:00 UTC 2019: fatal: Dirty repository: Having uncommitted changes. Exiting... 
```

What can we do to fix this ?

**Comment by orbex** [comment]
OK, thanks for the quick response.
Will investigate on our end.

**Comment by SamanthaAdrichem** [comment]
@goetas unfortunatly it has nothing to do with pipelines.

A small (for us) reproducable concept:

```
{
	"config": {
		"process-timeout": 600
	},
	"minimum-stability": "dev",
	"prefer-stable" : true,
	"require": {
		"riverline/multipart-parser": "2.0.2"
	}
}
```

then run (on a linux machine)
`composer update --prefer-source`

then
```
cd vendor/riverline/multipart-parser
git status
```

this will show the following files modified

> # Not currently on any branch.
> # Changes not staged for commit:
> #   (use "git add <file>..." to update what will be committed)
> #   (use "git checkout -- <file>..." to discard changes in working directory)
> #
> #       modified:   tests/data/email_base64.txt
> #       modified:   tests/data/nested_multipart.txt
> #       modified:   tests/data/no_boundary.txt
> #       modified:   tests/data/no_first_boundary.txt
> #       modified:   tests/data/no_last_boundary.txt
> #       modified:   tests/data/no_multipart.txt
> #
> 

git diff -w (ignore whitespace) shows no changes.
normal git diff shows the full file changed, but not really anything looks different

**Comment by rcambien** [comment]
Hi Samantha,

I think that it may be your IDE that changed those files because they use Windows end of line (\r\n) and the IDE changed them to Unix (\n).

Can you provide a git diff of those files to confirm this ?

**Comment by SamanthaAdrichem** [comment]
@rcambien i've only followed my description above, this means i never opened any editor. A workmate of mine did some digging with a hex viewer of the file. It seems the files contain special characters like the delete character, which seems that git diff wrongly parses this.

it seems like the solution could be to add a .gitattributes file with the following
`tests/data/*.txt binary`

this should treat all these files as binary

**Comment by SamanthaAdrichem** [comment]
Given pull request fixes it for us

try cloning this repo on a linux machine by just performing git clone and you will see that the files are modified instantly, clone my pull request and everything is fine!

**Comment by SamanthaAdrichem** [comment]
See new pull request, this should fix it all. (line endings only)
