### ISSUE TITLE
Suggestions for use in production upload cases?

### ISSUE THREAD

**Issue by bobmagicii** [Riverline/multipart-parser#27]
The thing that brought me here is that php://input contains multi-part form data when the HTTP verb is anything but POST - however the payload delivered does not contain the HTTP headers you use to check if it is a multi-part dataset, so passing it fopen('php://input','r') results in it not even attempting to parse it, claiming its not a multipart stream.

How would you suggest using the parser in the context of that?

**Comment by goetas** [comment]
The problem is that when PHP detects a `multipart/form-data`, the header `Content-Type` is removed/changed, so this library is not able to find the "boundary" used to split the message parts.

This is a special handling PHP does only with  `multipart/form-data` (that is a file upload form..)

**Comment by bobmagicii** [comment]
would it be possible to add a method to force it into understanding "this is a multipart" and then just read the first line of the data to acquire the boundary? not at my work pc atm to see the exact format but it seemed rather reliable. would such a feature be accepted if i was to submit a pull request?

**Comment by rcambien** [comment]
You can use the globals converter, it read the $_SERVER variables for header informations and get data from php://input.

```php
$part = Riverline\MultiPartParser\Converters\Globals::convert();
```
